name: Check PR title for commit convention

on:
  merge_group:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/github-script@v6
        with:
          script: |
            const msg = if (context.payload.pull_request) { context.payload.pull_request.title }
               else { context.payload.merge_group.head_commit.message };
            if (!/^(feat|fix|doc|style|refactor|test|chore|perf): .*[^.]($|\n\n)/.test(msg)) {
              core.setFailed('PR title does not follow the Commit Convention (https://leanprover.github.io/lean4/doc/dev/commit_convention.html).');
            }
