name: Update stage0
on:
  push:
    branches:
      - 'master'

concurrency:
  group: stage0
  cancel-in-progress: true

jobs:
  update-stage0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Install Cachix
      uses: cachix/cachix-action@v12
      with:
        name: lean4
    - run: nix build .#update-stage0-commit
    - run: nix run .#update-stage0-commit
    - run: git show --stat
    - run: git push origin HEAD:master
