name: Update stage0
on:
  push:
    branches:
      - 'master'

concurrency:
  group: stage0
  cancel-in-progress: true

jobs:
  update-stage0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # This action runs rarely, so the cache is only really useful when working
    # on this action. But then it is really useful
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = file://${{ github.workspace }}/nix-store-cache-copy?priority=10&trusted=true https://cache.nixos.org
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Install Cachix
      uses: cachix/cachix-action@v12
      with:
        name: lean4
    - run: nix build .#update-stage0
    - run: nix run .#update-stage0
    #- name: push code to master
    #  run: git push origin HEAD:master
